src/Entity/Contrat.php
<?php

namespace App\Entity;

use App\Repository\ContratRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ContratRepository::class)]
class Contrat
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTime $date_deb = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTime $date_fin = null;

    #[ORM\Column(length: 255)]
    private ?string $type_de_contrat = null;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    private ?Voiture $matricule = null;

    #[ORM\Column(length: 255)]
    private ?string $image = null;

    #[ORM\ManyToOne]
    private ?User $client = null;

    #[ORM\Column(length: 255)]
    private ?string $paymentLink = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateDeb(): ?\DateTime
    {
        return $this->date_deb;
    }

    public function setDateDeb(\DateTime $date_deb): self
    {
        $this->date_deb = $date_deb;

        return $this;
    }

    public function getDateFin(): ?\DateTime
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTime $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    public function getTypeDeContrat(): ?string
    {
        return $this->type_de_contrat;
    }

    public function setTypeDeContrat(string $type_de_contrat): self
    {
        $this->type_de_contrat = $type_de_contrat;

        return $this;
    }

    public function getMatricule(): ?Voiture
    {
        return $this->matricule;
    }

    public function setMatricule(?Voiture $matricule): self
    {
        $this->matricule = $matricule;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getClient(): ?User
    {
        return $this->client;
    }

    public function setClient(?User $client): self
    {
        $this->client = $client;

        return $this;
    }

    public function getPaymentLink(): ?string
    {
        return $this->paymentLink;
    }

    public function setPaymentLink(string $paymentLink): self
    {
        $this->paymentLink = $paymentLink;

        return $this;
    }
}

src/Form/ContratType.php
<?php

namespace App\Form;

use App\Entity\Contrat;
use App\Entity\Voiture;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\Regex;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;


class ContratType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
        
            // ->add('date_fin')
            ->add('periode',ChoiceType::class, [
                'choices'  => [
                    '3 mois' => '3M',
                    '6 mois' => '6M',
                    '12 mois' => '12M',
                ],
                'mapped'=>false,
            ])
            ->add('paymentLink', null, [
                'constraints' => [
                   
                   
                ],])
            // ->add('type_de_contrat'
            // ,TextType::class, [
    
            //     'constraints' => [
            //         new NotBlank(),
            //         new Regex([
            //             'pattern'=>'/^[a-zA-Z0-9 ]+$/',
            //             'message'=>'le lieux doit contenir que des nombres et caracteres'
                    
            //     ]),
            
            //     ]
               // ])
            //    $form->handleRequest($request);
            //    $badWords = $this->filterwords($Commentaire->getContenuCommentairer() . ' ' . $Commentaire->getContenuCommentairer());
            //    if (strpos($badWords, '**') !== false) {
            //     $this->addFlash('info', 'Faites attention a ce que vous tapez  ! un peu de respect !!');
            //    }
                ->add('type_de_contrat',ChoiceType::class, [
                    'choices'  => [
                        'assurance au tiers' => 'assurance au tiers',
                        'assurance au tiers plus' => 'assurance au tiers plus',
                        'assurance tous risques' => 'assurance tous risques',
                        
                        // $this->addFlash('info', 'Faites attention a ce que vous tapez  ! un peu de respect !!')


                    ],
                    //'mapped'=>false,
                ])
                
                // ->add('public', CheckboxType::class, [
                //     'label'    => 'Show this entry publicly?',
                //     'required' => false,
                // ])
            ->add('matricule',EntityType::class, [
                // looks for choices from this entity
                'class' => Voiture::class,
                // uses the User.username property as the visible option string
                'choice_label' => 'matricule',
                // used to render a select box, check boxes or radios
                'multiple' => false,
                'expanded' => false,
            ])
            ->add('image', FileType::class, [
                'label' => 'votre image de profil (Image file)',
                'mapped' => false,
                'required' => false,
                'constraints' => [
                    new File([
                        'maxSize' => '100000k',
                        'mimeTypes' => [
                            'image/gif',
                            'image/jpeg',
                            'image/jpg',
                        ],
                        'mimeTypesMessage' => 'Please upload a valid Image',
                    ])
                ],
            ])

        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Contrat::class,
        ]);
    }
}

src/Controller/ContratController.php
<?php

namespace App\Controller;

use App\Entity\Contrat;
use App\Entity\Voiture;
use App\Form\ContratType;
use App\Repository\ContratRepository;
use App\Repository\VoitureRepository;
use App\Service\SendMailService;
use DateTime;
use DateTimeImmutable;
use Doctrine\Common\Lexer\Token;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;
use Dompdf\Dompdf;
use Dompdf\Options;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Serializer\SerializerInterface;
use Symfony\Flex\Options as FlexOptions;
use Stripe\Stripe;
#[Route('/contrat')]
class ContratController extends AbstractController
{
    #[Route('/', name: 'app_contrat_index', methods: ['GET'])]
    public function index(ContratRepository $contratRepository): Response
    {
        
        return $this->render('contrat/index.html.twig', [
            'contrats' => $contratRepository->findAll(),
        ]);

    }
    
    #[Route('/frontContrat', name: 'app_contrat_indexfront', methods: ['GET'])]
    public function indexC(ContratRepository $contratRepository): Response
    {
        return $this->render('front/indexContrat.html.twig', [
            'contrats' => $contratRepository->findAll(),
        ]);
    }
    #[Route('/contratmobile', name: 'app_contratmobile', methods: ['GET'])]
    public function contratmob(ContratRepository $contratRepository,SerializerInterface $serializerInterface): Response
    {
        $contrats =$contratRepository->findAll();
        $json=$serializerInterface->serialize($contrats,'json');
return new Response($json);

    }

    
    #[Route('/new', name: 'app_contrat_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ContratRepository $contratRepository,SluggerInterface $slugger,SendMailService $mail): Response
    {
        $contrat = new Contrat();
        $form = $this->createForm(ContratType::class, $contrat);
        $form->handleRequest($request);
        
        $test=$request->get('contrat');
        if ($form->isSubmitted() && $form->isValid()) {
            $currentDate = new DateTime();
            $currentDate->format('Y-m-d ');
            $contrat->setDateDeb($currentDate);
            // $currentDate = new DateTimeImmutable();
            //     $currentDate->format('Y-m-d H:i:s');
            //     $currentDate->add(new DateInterval('P1D'));
            //     dd($currentDate);
            $date = new DateTime();
             $date->add(new \DateInterval('P'.$test['periode']));
            $contrat->setDateFin($date);
// partie image
$image = $form->get('image')->getData();
            
            

            // this condition is needed because the 'brochure' field is not required
            // so the PDF file must be processed only when a file is uploaded
            if ($image) {
                $originalFilename = pathinfo($image->getClientOriginalName(), PATHINFO_FILENAME);
                // this is needed to safely include the file name as part of the URL
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename.'-'.uniqid().'.'.$image->guessExtension();

                // Move the file to the directory where brochures are stored
                try {
                    $image->move(
                        $this->getParameter('contrat_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                }

                // updates the 'brochureFilename' property to store the PDF file name
                // instead of its contents
                $contrat->setimage($newFilename);
            }
            $contratRepository->save($contrat, true);
            /**************user */
            $email=$request->get('email');
            /******** */
            $mail->send(
            'aymen.benbrahim@esprit.tn',
            $email,
            'Contrat',
            'contrat/listcontrat.html.twig',
            [
                'contrat'=>$contrat
            ]
            
        );

            return $this->redirectToRoute('app_contrat_index', [], Response::HTTP_SEE_OTHER);




         
        }

        return $this->renderForm('contrat/new.html.twig', [
            'contrat' => $contrat,
            'form' => $form,
        ]);
    }

    #[Route('/front/newcontrat', name: 'app_contrat_new_front', methods: ['GET', 'POST'])]
    public function newC(Request $request, ContratRepository $contratRepository,SluggerInterface $slugger,SendMailService $mail): Response
    {
        $contrat = new Contrat();
        $form = $this->createForm(ContratType::class, $contrat);
        $form->handleRequest($request);
        
        $test=$request->get('contrat');
        if ($form->isSubmitted() && $form->isValid()) {
            $currentDate = new DateTime();
            $currentDate->format('Y-m-d ');
            $contrat->setDateDeb($currentDate);
            // $currentDate = new DateTimeImmutable();
            //     $currentDate->format('Y-m-d H:i:s');
            //     $currentDate->add(new DateInterval('P1D'));
            //     dd($currentDate);
            $date = new DateTime();
             $date->add(new \DateInterval('P'.$test['periode']));
            $contrat->setDateFin($date);
            // partie image
            $image = $form->get('image')->getData();
            
            

            if ($image) {
                $originalFilename = pathinfo($image->getClientOriginalName(), PATHINFO_FILENAME);
                // this is needed to safely include the file name as part of the URL
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename.'-'.uniqid().'.'.$image->guessExtension();

                // Move the file to the directory where brochures are stored
                try {
                    $image->move(
                        $this->getParameter('contrat_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                }

                $contrat->setimage($newFilename);
            }
            $contratRepository->save($contrat, true);
            /**************user */
            $email=$request->get('email');
            /******** */
            $mail->send(
            'aymen.benbrahim@esprit.tn',
            $email,
            'Contrat',
            'contrat/listcontrat.html.twig',
            [
                'contrat'=>$contrat
            ]
            
        );

            return $this->redirectToRoute('app_contrat_indexfront', [], Response::HTTP_SEE_OTHER);




         
        }

        return $this->renderForm('front/newContrat.html.twig', [
            'contrat' => $contrat,
            'form' => $form,
        ]);
    }

    /************************mobil supp*************************************** */
    #[Route('/suppMobil/{id}', name: 'app_contrat_suppMobil', methods: ['POST','GET'])]
    public function suppMobil(Contrat $contrat, ContratRepository $contratRepository,SerializerInterface $serializerInterface): Response
    {

            $contratRepository->remove($contrat, true);
            $json=$serializerInterface->serialize($contrat,'json');
    return new Response("Contrat deleted successfully" .$json);
    }
    
    /*****************************add mobil**************************************** */
    #[Route('/addMobil', name: 'app_contrat_addMobil', methods: ['GET', 'POST'])]
    public function addMobil(Request $request, ContratRepository $contratRepository,SerializerInterface $serializerInterface,VoitureRepository $voitureRepository)
    {
        $currentDate = new DateTime();
        $currentDate->format('Y-m-d ');
  
        $date = new DateTime();
         $date->add(new \DateInterval('P'.$request->get('periode')));
        $contrat= new Contrat();
        $contrat->setDateDeb($currentDate);
        $contrat->setDateFin($date);
        $contrat->setTypeDeContrat($request->get('type'));
        $contrat->setImage($request->get('image'));

        $voiture=new Voiture();
        $voiture=$voitureRepository->findOneByMatricule($request->get('mat'));

        $contrat->setMatricule($voiture);
        $contratRepository->save($contrat,true);
        $json=$serializerInterface->serialize($contrat,'json');
        return new Response("Contrat added successfully" .$json);
        


    }

    #[Route('/{id}/pdf', name: 'app_contrat_pdf')]

        public function generatePdfAction($id, ContratRepository $cr)
        {
            // Récupérez les informations de la commande correspondant à l'ID
            $contrat = $cr->findContratById($id);
            
            // Générez le contenu HTML à partir des informations de la commande
            $html = $this->renderView('contrat/listcontrat.html.twig', ['contrat' => $contrat]);
    
            // Générez le PDF à partir du contenu HTML
            $dompdf = new Dompdf();
            $dompdf->loadHtml($html);
            $dompdf->setPaper('A4', 'portrait');
            $dompdf->render();
            $pdfContent = $dompdf->output();
            
            // Renvoyez le PDF en tant que réponse HTTP
            $response = new Response();
            $response->headers->set('Content-Type', 'application/pdf');
            $response->setContent($pdfContent);
            return $response;
        }
        // $pdfOptions = new Options();

templates/contrat/_delete_form.html.twig
<form method="post" action="{{ path('app_contrat_delete', {'id': contrat.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ contrat.id) }}">
    <button class="btn">Delete</button>
</form>

templates/contrat/_form.html.twig
    <div class="pagetitle">
      <h1>Form Layouts</h1>
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="index.html">Home</a></li>
          
        </ol>
      </nav>
    </div><!-- End Page Title -->
    <section class="section">
      <div >
        <div class="col-lg-6">

          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Add contrat </h5>
              {{ form_start(form,{'attr':{'novalidate':'novalidate'}}) }}
              {{ form_row(form.paymentLink, {'attr': {'class': 'form-control mb-3', 'placeholder': 'enter the payment link'}}) }}
    {{ form_widget(form) }}
<input type="email" name="email" placeholder="Enter Email" id="inputEmail" class="form-control" autocomplete="email" required autofocus>


    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}
   </div>
            
          </div>

          

        </div>

        
      </div>
    </section>

templates/contrat/edit.html.twig
{% extends 'back/base.html.twig' %}

{% block title %}Edit Contrat{% endblock %}

{% block body %}
    <h1>Edit Contrat</h1>

    {{ include('contrat/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_contrat_index') }}">back to list</a>

    {{ include('contrat/_delete_form.html.twig') }}
{% endblock %}

templates/contrat/index.html.twig
{% extends 'back/base.html.twig' %}

{% block title %}Contrat{% endblock %}

{% block body %}
<div class="container" style="width:900px;margin-top:80px;">
    <h1>Contrat</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Date_deb</th>
                <th>Date_fin</th>
                <th>Type_de_contrat</th>
                <th>Image</th>
                <th >actions</th>
            </tr>
        </thead>
        <tbody>
        {% for contrat in contrats %}
            <tr>
                <td>{{ contrat.id }}</td>
                <td>{{ contrat.dateDeb ? contrat.dateDeb|date('Y-m-d') : '' }}</td>
                <td>{{ contrat.dateFin ? contrat.dateFin|date('Y-m-d') : '' }}</td>
                <td>{{ contrat.typeDeContrat }}</td>
                                                <td><img width="70" src="{{asset('uploads/'~ contrat.image)}}" ></td>

                <td>
                    <a href="{{ path('app_contrat_show', {'id': contrat.id}) }}">show</a>
                    <a href="{{ path('app_contrat_edit', {'id': contrat.id}) }}">edit</a>
                                        <a href="{{ contrat.paymentLink }}">edit</a>

                </td>
                                <td>     <a href="{{ path('app_contrat_pdf',{'id':contrat.id}) }}">PDF</a></td>


            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_contrat_new') }}">Create new</a>
       

<div >

{% endblock %}

templates/contrat/listcontrat.html.twig
{% block body %}
{# <div class="container" style="width:900px;margin-top:80px;">#}
<style>
		/* table {
			border-collapse: collapse;
			width: 100%;
			margin-bottom: 20px;
			border: 1px solid #ddd;
			font-size: 16px;
		} */
		/* th, td {
			text-align: left;
			padding: 12px;
			border-bottom: 1px solid #ddd;
		}
		th {
						width: 100%;

			background-color: #f2f2f2;
		}
		tr:hover {
						width: 100%;

			background-color: #white;
		} */
        body {
			font-family: Arial, sans-serif;
			font-size: 14px;
			line-height: 1.5;
		}
		.attestation {
			margin: 0 auto;
			padding: 20px;
			border: 2px solid #000;
			max-width: 600px;
		}
		.attestation h1 {
			font-size: 20px;
			font-weight: bold;
			text-align: center;
			margin-bottom: 20px;
		}
		.attestation p {
			text-align: justify;
			margin-bottom: 10px;
		}
		.attestation p.contract-id {
			text-align: center;
			font-weight: bold;
			font-size: 18px;
			margin-bottom: 30px;
		}
		footer {
			text-align: right;
			font-style: italic;
			margin-top: 30px;
		}
	</style>

    {# <h1 aligne="center">attestation d'assurance</h1>  #}
 <body>
<center border="0">
<div  style="background-color:white;"class="attestation">
    	<h1 style="color:black;"> attestation d'assurance</h1>

<p style="color:black;" class="contract-id">Numero contrat :"{{ contrat.id }}"</p></center>

    <table class="table table-hover">
        <thead>
        <tr>
        


            <tr>
                <th   >Date_deb</th>
                <th   >Date_fin</th>
                <th>Type_de_contrat</th>
                <th>Matricule </th>
                 <th>Nombre de places </th>
                <th>Puissance </th>
                 <th>Energie </th>
              <th>email</th>
                {# <th>Image</th>
                <th>actions</th> #}
            </tr>
        </thead>
        <tbody>
       
            <tr>
                <td>{{ contrat.dateDeb ? contrat.dateDeb|date('Y-m-d') : '' }}</td>
                <td>{{ contrat.dateFin ? contrat.dateFin|date('Y-m-d') : '' }}</td>
                 <td>{{ contrat.typedecontrat }}</td> 

                <td>{{ contrat.matricule.matricule }}</td>
                 <td>{{ contrat.matricule.Nombredeplaces }}</td> 
                <td>{{ contrat.matricule.Puissance }}</td>
                <td>{{ contrat.matricule.Energie }}</td>
				<td>{{ contrat.client.email }}</td>
                </tr>
                         {# <td><img width="70" src="{{asset('uploads/'~ contrat.image)}}" ></td>

                <td>
                    <a href="{{ path('app_contrat_show', {'id': contrat.id}) }}">show</a>
                    <a href="{{ path('app_contrat_edit', {'id': contrat.id}) }}">edit</a>
                </td>

            </tr>
        {% else %} #}
            
            
      
        </tbody>
    </table>
</div>
                       		<footer> Signature :</footer>

</div>
<body>
{% endblock %}

templates/contrat/new.html.twig
{% extends 'back/base.html.twig' %}

{% block title %}New Contrat{% endblock %}

{% block body %}
    <h1>Create new Contrat</h1>
    <center>
    {{ include('contrat/_form.html.twig') }}

    <a href="{{ path('app_contrat_index') }}">back to list</a>
    </center>

{% endblock %}

templates/contrat/show.html.twig
{% extends 'back/base.html.twig' %}

{% block title %}Contrat{% endblock %}

{% block body %}
    <h1>Contrat</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ contrat.id }}</td>
            </tr>
            <tr>
                <th>Date_deb</th>
                <td>{{ contrat.dateDeb ? contrat.dateDeb|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Date_fin</th>
                <td>{{ contrat.dateFin ? contrat.dateFin|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Type_de_contrat</th>
                <td>{{ contrat.typeDeContrat }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_contrat_index') }}">back to list</a>

    <a href="{{ path('app_contrat_edit', {'id': contrat.id}) }}">edit</a>

    {{ include('contrat/_delete_form.html.twig') }}
{% endblock %}